defaultNote:
  title: 'The default note'
  text: 'This is the default note for the demo application'

assets:
  overrides:
    /: ../frontend/


server:
  rootPath: /api/*
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080


template: Hello, %s!
defaultName: Stranger


# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password:

  # the JDBC URL
  url: jdbc:h2:~/test